spring:
  application:
    name: sathish-logger

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never

logging:
  level:
    root: INFO
    me.sathish.logger: INFO
