spring:
  application:
    name: my-github-cleaner
  config:
    import:
      - optional:file:.env[.properties]
      - configserver:${CONFIG_SERVER_URL}
  cloud:
    config:
      username: ${SPRING_CLOUD_CONFIG_USERNAME}
      password: ${SPRING_CLOUD_CONFIG_PASSWORD}
      fail-fast: true
      retry:
        max-attempts: 10
        initial-interval: 1000
        max-interval: 1500
        multiplier: 1.2
  docker:
    compose:
      enabled: false
      lifecycle-management: none

logging:
  level:
    root: ${LOG_LEVEL:INFO}
    me.sathish.my_github_cleaner: ${APP_LOG_LEVEL:INFO}
    org.springframework.web: ${WEB_LOG_LEVEL:INFO}
    org.hibernate.SQL: ${HIBERNATE_SQL_LEVEL:WARN}
    org.hibernate.type.descriptor.sql: ${HIBERNATE_TYPE_LEVEL:WARN}
    org.hibernate.stat: WARN
    org.hibernate.tool.hbm2ddl: WARN
    org.hibernate.engine.internal: WARN
    org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl: WARN
    com.zaxxer.hikari: ERROR
    sun.rmi: WARN
    javax.management.remote.rmi: WARN
    java.net.http: WARN

sathishlogger:
  enabled: ${SATHISHLOGGER_ENABLED:false}
  url: ${SATHISHLOGGER_URL}
  application-name: ${SATHISHLOGGER_APP_NAME}
